// Classic 3OS : chargement réel, AA du guest, réglages 3FS, TSG-3 et Finder.
const assert=require('assert'),fs=require('fs'),path=require('path');
const {connect,sleep}=require('./cdp.cjs');
(async()=>{
  const b=await connect(),{cdp,ev,until}=b;
  const url='http://127.0.0.1:'+(process.env.TRI27_HTTP||8124)+'/web/index.html?boot=3os';
  await cdp('Emulation.setDeviceMetricsOverride',{width:2200,height:1500,deviceScaleFactor:1,mobile:false});
  await cdp('Page.navigate',{url});
  await until(()=>ev("typeof W!=='undefined'&&W&&$('bootScreen').hidden"),'premier bureau',400);
  await ev("for(const k of Object.keys(localStorage))if(k.startsWith('3os.disk:'))localStorage.removeItem(k)");
  await cdp('Network.emulateNetworkConditions',{offline:false,latency:1200,downloadThroughput:-1,uploadThroughput:-1});
  await cdp('Page.navigate',{url});
  await until(()=>ev("!!document.getElementById('bootScreen')&&!document.getElementById('bootScreen').hidden"),'logo pendant vrai chargement');
  assert.equal(await ev("document.getElementById('bootScreen').getAttribute('aria-busy')"),'true');
  await b.shot('classic-boot','bootCard');
  await cdp('Network.emulateNetworkConditions',{offline:false,latency:0,downloadThroughput:-1,uploadThroughput:-1});
  await until(()=>ev("typeof W!=='undefined'&&W&&$('bootScreen').hidden&&conText.includes('[3OS] desktop-ready')"),'bureau pret',400);
  console.log('PASS logo/loading visible pendant le téléchargement réel ; masqué par desktop-ready');
  const scale=()=>ev('canvas.width===576?1:2');
  const pointer=async(type,x,y,buttons=0)=>{
    const u=await scale(),r=await ev('(()=>{const r=canvas.getBoundingClientRect();return{x:r.x,y:r.y,w:r.width,h:r.height,cw:canvas.width,ch:canvas.height}})()');
    await cdp('Input.dispatchMouseEvent',{type,x:r.x+x*u*r.w/r.cw,y:r.y+y*u*r.h/r.ch,button:type==='mouseMoved'?'none':'left',buttons,clickCount:1});
  };
  const click=async(x,y,delay=300)=>{await pointer('mouseMoved',x,y);await sleep(70);await pointer('mousePressed',x,y,1);await sleep(140);await pointer('mouseReleased',x,y);await sleep(delay);};
  const key=async(k,c)=>{await ev('canvas.focus()');await cdp('Input.dispatchKeyEvent',{type:'keyDown',key:k,windowsVirtualKeyCode:c});await sleep(100);await cdp('Input.dispatchKeyEvent',{type:'keyUp',key:k,windowsVirtualKeyCode:c});await sleep(300);};
  const rgb=async(x,y)=>{const u=await scale();return ev(`Array.from(ctx.getImageData(${x*u},${y*u},1,1).data).slice(0,3)`);};
  const readFile=name=>ev(`(()=>{const d=new Int16Array(W.memory.buffer,W.disk_ptr(),W.disk_len()),word=p=>d[p]+3**9*d[p+1]+3**18*d[p+2];for(let i=0;i<word(3);i++){const p=6+i*30;let n='';for(let j=0;j<16&&d[p+j];j++)n+=String.fromCharCode(d[p+j]);if(n===${JSON.stringify(name)}){const start=word(p+16),len=word(p+19);let t='';for(let j=0;j<len;j++)t+=String.fromCharCode(d[start*729+j]);return t;}}return null})()`);
  const capture=async name=>{await pointer('mouseMoved',10,25);await sleep(250);const p=await ev("canvas.toDataURL('image/png').split(',')[1]");fs.writeFileSync(path.join(b.shotDir,name+'.png'),Buffer.from(p,'base64'));};
  const colors=()=>ev(`(()=>{const d=ctx.getImageData(682,500,400,20).data,s=new Set();for(let i=0;i<d.length;i+=4)s.add(d[i]+256*d[i+1]+65536*d[i+2]);return s.size})()`);
  await key('F4',115);await click(193,196);await until(()=>ev('canvas.width===1920'),'1080p',400);await key('Enter',13);
  await capture('classic-desktop');
  await key('F8',119);await capture('classic-fonts');
  assert(await colors()>=8,'pixels intermédiaires réels dans la fonte du framebuffer');
  await click(345,218);await until(async()=>await colors()<=2,'lissage vraiment coupé');
  await capture('classic-fonts-no-aa');
  await click(345,218);await until(async()=>await colors()>=8,'lissage rétabli');
  await click(500,132);await click(435,185);
  await until(async()=>/^1 1 16 1 /.test(await readFile('prefs')),'famille/taille sauvegardées sur 3FS',400);
  await capture('classic-fonts-mono16');
  await key('Escape',27);await key('F6',117);const oldDesk=await rgb(10,290);
  await click(520,142);await click(345,245);
  await until(async()=>/^1 1 16 1 1 1 /.test(await readFile('prefs')),'fond et motif sauvegardés');
  assert.notDeepEqual(await rgb(10,290),oldDesk,'le fond a réellement changé');await capture('classic-wallpaper');
  await key('Escape',27);await key('F7',118);await click(350,135);
  await until(async()=>/^1 1 16 1 1 1 0 /.test(await readFile('prefs')),'volume zéro réellement sauvegardé');
  const energy=()=>ev(`(()=>{const p=W.audio_render(4096),a=new Float32Array(W.memory.buffer,p,4096);let s=0,max=0;for(const v of a){s+=v*v;max=Math.max(max,Math.abs(v));}return{rms:Math.sqrt(s/a.length),max}})()`);
  await click(360,202,30);await ev('running=false');const muted=await energy();await ev('running=true');assert.equal(muted.max,0);
  await click(455,135);await click(360,202,30);await ev('running=false');const audible=await energy();await ev('running=true');assert(audible.rms>0.0001,JSON.stringify(audible));
  assert.equal(await ev('actx.state'),'running','AudioContext déverrouillé par vrai geste utilisateur');
  await click(350,135);await capture('classic-sound');
  const prefs=await readFile('prefs');assert.equal(prefs,'1 1 16 1 1 1 0 1\n');
  console.log('PASS fond/motif, deux familles, taille, AA on/off, master TSG-3 :',JSON.stringify({muted,audible,prefs}));
  await key('Escape',27);await click(15,10);await capture('classic-system-menu');await key('Escape',27);
  await click(915,10);await capture('classic-finder-menu');await click(790,154);
  await until(()=>ev("conText.includes('Hello from TRI-27')"),'vrai lancement de hello depuis Finder',400);
  assert.equal(await readFile('prefs'),prefs);
  console.log('PASS menu système et Finder : hello exécuté par sys_exec, préférences conservées');
  await until(()=>ev("Object.keys(localStorage).some(k=>k.startsWith('3os.disk:'))"),'disque sauvegardé dans le navigateur');
  await cdp('Page.navigate',{url});
  await until(()=>ev("typeof W!=='undefined'&&W&&canvas.width===1920&&$('bootScreen').hidden"),'vrai rechargement',400);
  assert.equal(await readFile('prefs'),prefs);
  await key('F8',119);assert(await colors()>=8);await capture('classic-persisted-fonts');await key('Escape',27);
  await capture('classic-persisted-desktop');
  assert.equal(b.exceptions.length,0,b.exceptions.join('\n'));console.log('PASS rechargement : prefs 3FS exactes, AA et fond visibles, aucune exception JS');
  await ev("for(const k of Object.keys(localStorage))if(k.startsWith('3os.disk:'))localStorage.removeItem(k)");
  await cdp('Emulation.clearDeviceMetricsOverride');b.close();process.exit(0);
})().catch(e=>{console.error(e.stack);process.exit(1)});
