// Molette réelle CDP : fenêtres sous le pointeur, zoom guest ancré, pan et reset.
const assert=require('assert'),fs=require('fs'),path=require('path');
const {connect,sleep}=require('./cdp.cjs');
(async()=>{
  const b=await connect(),{cdp,ev,until}=b;
  await cdp('Emulation.setDeviceMetricsOverride',{width:1500,height:1000,deviceScaleFactor:1,mobile:false});
  await cdp('Page.navigate',{url:'http://127.0.0.1:'+(process.env.TRI27_HTTP||8124)+'/web/?boot=3os'});
  await until(()=>ev("typeof W!=='undefined'&&W&&typeof diskReady!=='undefined'"),'WASM');
  await ev("(async()=>{running=false;await diskReady;for(const k of Object.keys(localStorage))if(k.startsWith('3os.disk:'))localStorage.removeItem(k);diskImage=new Int16Array(await(await fetch('../os/3os.t3d',{cache:'no-store'})).arrayBuffer());await assembleAndRun();canvas.addEventListener('wheel',e=>window.testWheelPrevented=e.defaultPrevented);})()");
  await until(()=>ev('W.frames()>=2&&canvas.width===576'),'bureau');
  const pos=async(x,y)=>{const r=await ev('(()=>{const r=canvas.getBoundingClientRect();return{x:r.x,y:r.y,w:r.width,h:r.height}})()');return{x:r.x+x*r.w/576,y:r.y+y*r.h/360};};
  const wheel=async(x,y,dy)=>{await cdp('Input.dispatchMouseEvent',{...await pos(x,y),type:'mouseWheel',deltaX:0,deltaY:dy,buttons:0});await sleep(180);};
  const key=async(k,c)=>{await ev('canvas.focus()');await cdp('Input.dispatchKeyEvent',{type:'keyDown',key:k,windowsVirtualKeyCode:c});await sleep(70);await cdp('Input.dispatchKeyEvent',{type:'keyUp',key:k,windowsVirtualKeyCode:c});await sleep(150);};
  const mouse=async(type,x,y,buttons=0)=>{await cdp('Input.dispatchMouseEvent',{...await pos(x,y),type,button:type==='mouseMoved'?'none':'left',buttons,clickCount:1});await sleep(100);};
  const hash=(x,y,w,h)=>ev(`(()=>{const d=ctx.getImageData(${x},${y},${w},${h}).data;let z=0;for(const v of d)z=(Math.imul(z,31)+v)>>>0;return z})()`);
  const rgb=(x,y)=>ev(`Array.from(ctx.getImageData(${x},${y},1,1).data).slice(0,3)`);
  const finder=()=>hash(55,110,225,175),help=()=>hash(365,150,145,120);
  const first=await finder();await wheel(315,160,120);
  await until(async()=>await finder()!==first,'molette Finder');
  await wheel(315,160,-120);await until(async()=>await finder()===first,'retour scroll Finder');
  await wheel(315,160,10000);const end=await finder();assert.notEqual(end,first);
  await wheel(315,160,10000);assert.equal(await finder(),end,'borne du scroll');
  const h0=await help();await wheel(535,180,120);await until(async()=>await help()!==h0,'molette document');
  await wheel(535,180,-120);await until(async()=>await help()===h0,'retour document');
  await wheel(560,40,-120);assert.equal(await finder(),end,'pas de scroll hors fenêtre');
  assert.equal(await ev('window.testWheelPrevented'),true,'pas de défilement de page hôte');
  await wheel(315,160,-10000);await until(async()=>await finder()===first,'scroll en haut');
  console.log('PASS wheel Finder/document, bornes, hover, page hôte inchangée');
  const files=await ev("(()=>{const d=new Int16Array(W.memory.buffer,W.disk_ptr(),W.disk_len()),word=p=>d[p]+3**9*d[p+1]+3**18*d[p+2],a=[];for(let i=0;i<word(3);i++){let n='';for(let k=0;k<16&&d[6+i*30+k];k++)n+=String.fromCharCode(d[6+i*30+k]);a.push(n)}return a})()");
  await mouse('mouseMoved',100,47);await mouse('mousePressed',100,47,1);await mouse('mouseReleased',100,47);
  await key('End',35);for(let i=files.length-1;i>files.indexOf('demo.png');i--)await key('ArrowUp',38);
  await ev("window.Image=class{constructor(){throw Error('host decoder forbidden')}};window.createImageBitmap=()=>Promise.reject(Error('host decoder forbidden'))");
  await key('Enter',13);await until(()=>ev("conText.includes('[images] demo.png 384 x 216 RGBA native')"),'visualiseur',900);
  const header=await hash(8,8,560,26),initial=await hash(6,58,564,264),anchor=await rgb(250,130);
  const span=()=>ev("(()=>{const p=ctx.getImageData(0,100,576,1).data,a=[];for(let x=0;x<576;x++){const c=p.slice(x*4,x*4+3);if(Math.max(...c)-Math.min(...c)>10)a.push(x)}return {left:a[0],right:a.at(-1),width:a.length}})()");
  const s0=await span();assert.equal(s0.width,384);
  let at=await ev('conText.length'),frame=await ev('W.frames()');
  await wheel(250,130,-40);await until(()=>ev(`conText.slice(${at}).includes('zoom zoom=125')&&W.frames()>${frame}`),'zoom 125',900);
  const s1=await span();assert.equal(s1.width,480);assert.equal(await hash(8,8,560,26),header,'UI non zoomée');
  assert.deepEqual(await ev('[canvas.width,canvas.height]'),[576,360]);
  const a1=await rgb(250,130);assert(a1.every((v,i)=>Math.abs(v-anchor[i])<=1),'point sous le curseur');
  await b.shot('wheel-image-125');
  at=await ev('conText.length');frame=await ev('W.frames()');
  await ev('W.set_wheel(-3)');
  await until(()=>ev(`conText.slice(${at}).includes('zoom zoom=300')&&W.frames()>${frame}`),'zoom 300',900);
  // Injecter dans une seule transaction hôte : exactement la même itération guest.
  at=await ev('conText.length');frame=await ev('W.frames()');
  await ev('W.set_wheel(-1);W.push_key(187)');
  await until(()=>ev(`conText.slice(${at}).includes('zoom zoom=400')&&W.frames()>${frame}`),'molette + touche à la borne haute',30);
  await wheel(250,130,-10000);
  await until(async()=>await hash(6,58,564,264)!==initial,'rendu zoom 400',900);
  const beforePan=await hash(6,58,564,264);at=await ev('conText.length');
  await mouse('mouseMoved',250,130);await mouse('mousePressed',250,130,1);await mouse('mouseMoved',300,160,1);await mouse('mouseReleased',300,160);
  await until(()=>ev(`conText.slice(${at}).includes('pan zoom=400')`),'pan',900);
  await until(async()=>await hash(6,58,564,264)!==beforePan,'pixels déplacés',900);
  await b.shot('wheel-image-pan');
  at=await ev('conText.length');await wheel(250,130,10000);await until(()=>ev(`conText.slice(${at}).includes('zoom zoom=25')`),'borne 25',900);
  await sleep(200);frame=await ev('W.frames()');await wheel(250,130,10000);assert.equal(await ev('W.frames()'),frame,'pas de redraw à la borne');
  at=await ev('conText.length');frame=await ev('W.frames()');await ev('W.set_wheel(-1)');
  await until(()=>ev(`conText.slice(${at}).includes('zoom zoom=50')&&W.frames()>${frame}`),'zoom 50',900);
  at=await ev('conText.length');frame=await ev('W.frames()');await ev('W.set_wheel(1);W.push_key(189)');
  await until(()=>ev(`conText.slice(${at}).includes('zoom zoom=25')&&W.frames()>${frame}`),'molette + touche à la borne basse',30);
  await key('0',48);await until(async()=>await hash(6,58,564,264)===initial,'reset 1:1',900);
  await wheel(100,20,-40);assert.equal(await hash(6,58,564,264),initial,'pas de zoom sur le titre');
  await key('Escape',27);await until(()=>ev('canvas.width===576&&canvas.height===360'),'retour bureau');
  assert.equal(b.exceptions.length,0,b.exceptions.join('\n'));
  fs.writeFileSync(path.join(b.shotDir,'wheel-native.json'),JSON.stringify({finder:true,document:true,hover:true,zoom:[25,100,125,400],rasterWidths:[s0.width,s1.width],anchorBefore:anchor,anchorAfter:a1,pan:true,reset:true,mixedZoomInputs:true,hostDecoderForbidden:true,exceptions:0},null,2));
  await cdp('Emulation.clearDeviceMetricsOverride');b.close();console.log('PASS wheel zoom 25–400, ancrage, pan, reset, UI native et exceptions 0');process.exit(0);
})().catch(e=>{console.error(e.stack);process.exit(1)});
